function applyKnockoutUpdate(){if(typeof state!=='undefined')state.dataLabel='MAJ 7 juillet • arbre bleu style tableau officiel';try{if(typeof save==='function')save()}catch(e){}}
const R16=[['Allemagne','Paraguay','1-1','tab 3-4','Paraguay'],['France','Suède','3-0','','France'],['Afrique du Sud','Canada','0-1','','Canada'],['Pays-Bas','Maroc','1-1','tab 2-3','Maroc'],['Portugal','Croatie','2-1','','Portugal'],['Espagne','Autriche','3-0','','Espagne'],['États-Unis','Bosnie','2-0','','États-Unis'],['Belgique','Sénégal','3-2','ap','Belgique'],['Brésil','Japon','2-1','','Brésil'],['Côte d’Ivoire','Norvège','1-2','','Norvège'],['Mexique','Équateur','2-0','','Mexique'],['Angleterre','RD Congo','2-1','','Angleterre'],['Argentine','Cap-Vert','3-2','','Argentine'],['Australie','Égypte','1-1','tab 2-4','Égypte'],['Suisse','Algérie','2-0','','Suisse'],['Colombie','Ghana','1-0','','Colombie']];
const R8=[['Maroc','Canada','3','0','Maroc','Terminé'],['France','Paraguay','1','0','France','Terminé'],['Norvège','Brésil','2','1','Norvège','Terminé'],['Angleterre','Mexique','3','2','Angleterre','Terminé'],['Espagne','Portugal','1','0','Espagne','Terminé'],['Belgique','États-Unis','4','1','Belgique','Terminé'],['Argentine','Égypte','','','', '18h00'],['Suisse','Colombie','','','', '22h00']];
const QF=[['Maroc','France','9 juillet'],['Angleterre','Norvège','11 juillet'],['Espagne','Belgique','10 juillet'],['Vainq. Argentine/Égypte','Vainq. Suisse/Colombie','À venir']];
function fl(t){return typeof flag==='function'?flag(t):''}function sh(t){return ({'Afrique du Sud':'Afrique S.','Côte d’Ivoire':'Côte Iv.','États-Unis':'USA','RD Congo':'RDC','Vainq. Argentine/Égypte':'Vainq. ARG/ÉGY','Vainq. Suisse/Colombie':'Vainq. SUI/COL'}[t]||t)}
function teamLine(name,score,win){return '<div class="br-team '+(win?'win':'')+'"><span>'+fl(name)+' '+sh(name)+'</span><b>'+score+'</b></div>'}
function card16(m,i){return '<div class="br-card small"><em>'+(i+1)+'</em>'+teamLine(m[0],m[2].split('-')[0],m[4]===m[0])+teamLine(m[1],m[2].split('-')[1]||'',m[4]===m[1])+(m[3]?'<small>'+m[3]+'</small>':'')+'</div>'}
function card8(m,i){let ok=m[5]==='Terminé';return '<div class="br-card mid"><em>8e '+(i+1)+'</em>'+teamLine(m[0],ok?m[2]:'-',ok&&m[4]===m[0])+teamLine(m[1],ok?m[3]:'-',ok&&m[4]===m[1])+'<small>'+(ok?'Qualifié : '+sh(m[4]):'À jouer '+m[5])+'</small></div>'}
function cardQ(q,i){return '<div class="br-card qf"><em>Quart '+(i+1)+'</em><div class="br-vs"><span>'+fl(q[0])+' '+sh(q[0])+'</span><strong>VS</strong><span>'+fl(q[1])+' '+sh(q[1])+'</span></div><small>'+q[2]+'</small></div>'}
function side(title,r16s,r8s,qfs,start){return '<section class="br-side"><h3>'+title+'</h3><div class="br-cols"><div class="br-col r16col"><h4>16es</h4>'+r16s.map((m,i)=>card16(m,start+i)).join('')+'</div><div class="br-col r8col"><h4>8es</h4>'+r8s.map((m,i)=>card8(m,start/2+i)).join('')+'</div><div class="br-col qfcol"><h4>Quarts</h4>'+qfs.map((q,i)=>cardQ(q,start/4+i)).join('')+'</div></div></section>'}
function renderTree(){return '<div class="blue-board"><div class="bb-head"><strong>COUPE DU MONDE 2026</strong><span>Phase finale • résultats mis à jour</span></div>'+side('Partie gauche du tableau',R16.slice(0,8),R8.slice(0,4),QF.slice(0,2),0)+'<div class="bb-final"><div class="bb-cup">🏆</div><strong>FINALE</strong><span>Vainqueur demi 1 vs vainqueur demi 2</span><small>19 juillet</small></div>'+side('Partie droite du tableau',R16.slice(8),R8.slice(4),QF.slice(2),8)+'</div>'}
function row16(m){let cls=m[0]==='Sénégal'||m[1]==='Sénégal'?'ko-result senegal-out':'ko-result';return '<div class="'+cls+'"><strong>'+m[0]+' - '+m[1]+'</strong><b>'+m[2]+'</b><em>Qualifié : '+m[4]+(m[3]?' • '+m[3]:'')+'</em></div>'}
function row8(m){let ok=m[5]==='Terminé';return '<div class="ko-result"><strong>'+m[0]+' - '+m[1]+'</strong><b>'+(ok?m[2]+'-'+m[3]:m[5])+'</b><em>'+(ok?'Qualifié : '+m[4]:'À jouer')+'</em></div>'}
function renderProjectedBracket(){return '<article class="card wide-card ko-card blue-phase"><h2 class="section-title">Phase finale</h2><p class="subtitle">Style tableau bleu officiel, scores visibles, poules conservées.</p><div class="ko-alert"><strong>MAJ 7 juillet</strong><span>Espagne 1-0 Portugal, Belgique 4-1 USA. Quarts : Maroc-France, Angleterre-Norvège, Espagne-Belgique.</span></div>'+renderTree()+'<details class="ko-details" open><summary>Résultats des 8es</summary><div class="ko-results">'+R8.map(row8).join('')+'</div></details><details class="ko-details"><summary>Résultats des 16es</summary><div class="ko-results">'+R16.map(row16).join('')+'</div></details></article>'}
setTimeout(function(){applyKnockoutUpdate();if(typeof render==='function')render();if(typeof updateDashboard==='function')updateDashboard()},120);