function applyKnockoutUpdate(){if(typeof state!=='undefined')state.dataLabel='MAJ maintenance 7 juillet • 8es en cours • poules conservees';try{if(typeof save==='function')save()}catch(e){}}
const R16=[['28/06','Afrique du Sud','Canada','0-1','Canada'],['29/06','Brésil','Japon','2-1','Brésil'],['29/06','Allemagne','Paraguay','1-1, 3-4 tab','Paraguay'],['30/06','Pays-Bas','Maroc','1-1, 2-3 tab','Maroc'],['30/06','Côte d’Ivoire','Norvège','1-2','Norvège'],['30/06','France','Suède','3-0','France'],['01/07','Mexique','Équateur','2-0','Mexique'],['01/07','Angleterre','RD Congo','2-1','Angleterre'],['01/07','Belgique','Sénégal','3-2 ap','Belgique'],['02/07','États-Unis','Bosnie','2-0','États-Unis'],['02/07','Espagne','Autriche','3-0','Espagne'],['03/07','Portugal','Croatie','2-1','Portugal'],['03/07','Suisse','Algérie','2-0','Suisse'],['03/07','Australie','Égypte','1-1, 2-4 tab','Égypte'],['04/07','Argentine','Cap-Vert','3-2','Argentine'],['04/07','Colombie','Ghana','1-0','Colombie']];
const R8=[['04/07','Canada','Maroc','0-3','Maroc','OK'],['04/07','Paraguay','France','0-1','France','OK'],['05/07','Brésil','Norvège','2-1','Norvège','OK'],['06/07','Mexique','Angleterre','2-3','Angleterre','OK'],['06/07','Portugal','Espagne','0-1','Espagne','OK'],['07/07','États-Unis','Belgique','1-4','Belgique','OK'],['07/07','Argentine','Égypte','18h00','','WAIT'],['07/07','Suisse','Colombie','22h00','','WAIT']];
const QF=[['Quart 1','Maroc','France','9 juillet'],['Quart 2','Angleterre','Norvège','11 juillet'],['Quart 3','Espagne','Belgique','10 juillet'],['Quart 4','Argentine/Égypte','Suisse/Colombie','À venir']];
function f(t){return typeof flag==='function'?flag(t):''}function s(t){return ({'Afrique du Sud':'Afrique S.','Côte d’Ivoire':'Côte Iv.','États-Unis':'USA','RD Congo':'RD Congo'}[t]||t)}function team(t){return f(t)+' '+s(t)}
function pair(a,b){return '<div class="tree-team"><span>'+team(a)+'</span><span>'+team(b)+'</span></div>'}
function card16(m,i){let cls=m[2]==='Sénégal'||m[1]==='Sénégal'?'tree-card senegal-out':'tree-card';return '<article class="'+cls+'"><div class="tree-head"><b>'+(i+1)+'</b><em>'+m[0]+'</em></div>'+pair(m[1],m[2])+'<strong class="tree-score">'+m[3]+'</strong><small>Qualifié : '+team(m[4])+'</small></article>'}
function card8(m,i){let done=m[5]==='OK';return '<article class="tree-card '+(done?'done':'')+'"><div class="tree-head"><b>'+String.fromCharCode(65+i)+'</b><em>'+m[0]+'</em></div>'+pair(m[1],m[2])+'<strong class="tree-score '+(done?'':'pending')+'">'+m[3]+'</strong><small>'+(done?'Qualifié : '+team(m[4]):'À jouer')+'</small></article>'}
function cardQ(m){return '<article class="tree-card qf '+(m[3]!=='À venir'?'done':'')+'"><div class="tree-head"><b>'+m[0]+'</b><em>'+m[3]+'</em></div>'+pair(m[1],m[2])+'</article>'}
function renderTree(){return '<div class="tree-wrap"><div class="tree-title">ARBRE PHASE FINALE</div><div class="tree-sub">MAJ 7 juillet • 6 huitièmes joués • 3 quarts confirmés</div><div class="tree-grid updated-tree"><section><h4>16es</h4><div class="tree-list">'+R16.slice(0,8).map(card16).join('')+'</div></section><section><h4>8es</h4><div class="tree-list tree-r8">'+R8.slice(0,4).map(card8).join('')+'</div></section><section><h4>Quarts</h4><div class="tree-list tree-qf">'+QF.map(cardQ).join('')+'<div class="tree-final">Finale<br><span>19/07</span></div></div></section><section><h4>8es</h4><div class="tree-list tree-r8">'+R8.slice(4).map(card8).join('')+'</div></section><section><h4>16es</h4><div class="tree-list">'+R16.slice(8).map(card16).join('')+'</div></section></div></div>'}
function row(m){let done=m.length===6?m[5]==='OK':true;return '<div class="ko-result '+(m[2]==='Sénégal'||m[1]==='Sénégal'?'senegal-out':'')+'"><span>'+m[0]+'</span><strong>'+m[1]+' - '+m[2]+'</strong><b>'+m[3]+'</b><em>'+(done?'Qualifié : '+m[4]:'À jouer')+'</em></div>'}
function renderProjectedBracket(){return '<article class="card wide-card ko-card"><h2 class="section-title">Phase finale</h2><p class="subtitle">MAJ maintenance 7 juillet : poules conservées, arbre phase finale mis à jour.</p><div class="ko-alert"><strong>Derniers résultats</strong><span>Espagne 1-0 Portugal, Belgique 4-1 États-Unis. Quarts confirmés : Maroc-France, Angleterre-Norvège, Espagne-Belgique.</span></div>'+renderTree()+'<h3 class="mini-title">Quarts confirmés</h3><div class="watch-list"><span>Maroc - France • 9 juillet</span><span>Angleterre - Norvège • 11 juillet</span><span>Espagne - Belgique • 10 juillet</span></div><details class="ko-details" open><summary>Résultats des 8es</summary><div class="ko-results">'+R8.map(row).join('')+'</div></details><details class="ko-details"><summary>Résultats des 16es</summary><div class="ko-results">'+R16.map(row).join('')+'</div></details><h3 class="mini-title">Derniers 8es aujourd’hui</h3><div class="watch-list"><span>Argentine - Égypte • 18h00</span><span>Suisse - Colombie • 22h00</span></div></article>'}
setTimeout(function(){applyKnockoutUpdate();if(typeof render==='function')render();if(typeof updateDashboard==='function')updateDashboard()},120);